### PR TITLE
chore: add tooling for linting, bumping, and releasing

### PR DESCRIPTION
**Pull request by TillaTheHun0**
This PR:
- Adds `husky`, `commitlint`, and `lint-staged` for code quality and commit message spec compliance. On each commit, the relevant code is linted and tested. Additionally the commit message is checked to be compliant with the [Conventional Commits Spec](https://www.conventionalcommits.org/en/v1.0.0/)
- Adds ~`standard-version`~ `semantic-release` for semantically tagging, and generating release notes. Exposed as the `npm` script `release`.

### CODE REVIEW

**Comment by TillaTheHun0** [comment]
@lgandecki I just swapped out `standard-version` for `semantic-release` based on our discussion about what you would like to happen on a release (just a git tag). `semantic-release` should work out of the box with this setup as we are still adhering to Angular Commit Style (Conventional Commits)

**Comment by TillaTheHun0** [comment]
@lgandecki any eyes on this?

**Comment by lgandecki** [comment]
not yet! Sorry. Super busy the last few days. worst-case scenario I will get this done the coming weekend.

**Comment by lgandecki** [comment]
I want to add the semantic-release separately so I took the previous commit from this branch, created a new branch and merged all that there - #17 . 
Thanks for your help!

**Pull request closed without merging**
